-- 第八课 PostgreSQL 18 专属：identity、RETURNING 与 UPSERT。
-- 安全说明：只修改会话临时表，事务末尾回滚。

CREATE TEMPORARY TABLE learning_postgresql_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  display_name VARCHAR(80) NOT NULL
);

BEGIN;

INSERT INTO learning_postgresql_contacts (email, display_name)
VALUES ('lin@example.com', '林夏')
RETURNING id, email, display_name;

INSERT INTO learning_postgresql_contacts (email, display_name)
VALUES ('lin@example.com', '林夏（更新）')
ON CONFLICT (email) DO UPDATE
SET display_name = EXCLUDED.display_name
RETURNING id, email, display_name;

SELECT id, email, display_name
FROM learning_postgresql_contacts
ORDER BY id;

ROLLBACK;

SELECT COUNT(*) AS contact_count_after_rollback
FROM learning_postgresql_contacts;
