-- PostgreSQL 18：用户、资料、地址、角色关系模型。
-- 仅在专用学习数据库运行；脚本不删除、截断或覆盖既有业务表。

CREATE SCHEMA IF NOT EXISTS learning14;

CREATE TABLE IF NOT EXISTS learning14.users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR(254) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_learning14_users PRIMARY KEY (user_id),
  CONSTRAINT uq_learning14_users_email UNIQUE (email),
  CONSTRAINT ck_learning14_users_status
    CHECK (status IN ('active', 'disabled'))
);

-- PostgreSQL 不会因 UPDATE 自动改 updated_at；应由明确 SQL 或受控触发器维护。
CREATE TABLE IF NOT EXISTS learning14.user_profiles (
  user_id BIGINT NOT NULL,
  bio VARCHAR(500),
  avatar_url VARCHAR(500),
  CONSTRAINT pk_learning14_user_profiles PRIMARY KEY (user_id),
  CONSTRAINT fk_learning14_profiles_user
    FOREIGN KEY (user_id)
    REFERENCES learning14.users (user_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS learning14.user_addresses (
  address_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  label VARCHAR(30) NOT NULL,
  country_code CHAR(2) NOT NULL,
  city VARCHAR(100) NOT NULL,
  address_detail VARCHAR(500) NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_learning14_user_addresses PRIMARY KEY (address_id),
  CONSTRAINT fk_learning14_addresses_user
    FOREIGN KEY (user_id)
    REFERENCES learning14.users (user_id)
    ON DELETE CASCADE,
  CONSTRAINT ck_learning14_addresses_country
    CHECK (char_length(country_code) = 2)
);

CREATE INDEX IF NOT EXISTS ix_learning14_addresses_user
  ON learning14.user_addresses (user_id, address_id);

CREATE TABLE IF NOT EXISTS learning14.roles (
  role_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  role_code VARCHAR(50) NOT NULL,
  role_name VARCHAR(100) NOT NULL,
  CONSTRAINT pk_learning14_roles PRIMARY KEY (role_id),
  CONSTRAINT uq_learning14_roles_code UNIQUE (role_code)
);

CREATE TABLE IF NOT EXISTS learning14.user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_learning14_user_roles PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_learning14_user_roles_user
    FOREIGN KEY (user_id)
    REFERENCES learning14.users (user_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_learning14_user_roles_role
    FOREIGN KEY (role_id)
    REFERENCES learning14.roles (role_id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_learning14_user_roles_role
  ON learning14.user_roles (role_id, user_id);

-- 从标准 information_schema 验证表约束。
SELECT
  tc.table_name,
  tc.constraint_name,
  tc.constraint_type
FROM information_schema.table_constraints AS tc
WHERE tc.table_schema = 'learning14'
ORDER BY tc.table_name, tc.constraint_type, tc.constraint_name;

-- 验证外键列与删除、更新动作。
SELECT
  kcu.table_name,
  kcu.column_name,
  ccu.table_name AS referenced_table_name,
  ccu.column_name AS referenced_column_name,
  rc.delete_rule,
  rc.update_rule
FROM information_schema.key_column_usage AS kcu
JOIN information_schema.referential_constraints AS rc
  ON rc.constraint_catalog = kcu.constraint_catalog
 AND rc.constraint_schema = kcu.constraint_schema
 AND rc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage AS ccu
  ON ccu.constraint_catalog = rc.unique_constraint_catalog
 AND ccu.constraint_schema = rc.unique_constraint_schema
 AND ccu.constraint_name = rc.unique_constraint_name
WHERE kcu.table_schema = 'learning14'
ORDER BY kcu.table_name, kcu.constraint_name, kcu.ordinal_position;
