-- 全栈数据库阶段项目：PostgreSQL
-- 仅在自己的学习数据库运行。
-- 本文件不删除对象或数据；表使用 capstone_ 前缀。

CREATE TABLE IF NOT EXISTS capstone_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(254) NOT NULL,
  display_name VARCHAR(80) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_capstone_users_email UNIQUE (email),
  CONSTRAINT chk_capstone_users_status
    CHECK (status IN ('active', 'disabled', 'pending'))
);

CREATE INDEX IF NOT EXISTS idx_capstone_users_status_created_id
  ON capstone_users (status, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS capstone_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(80) NOT NULL,
  CONSTRAINT uq_capstone_roles_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS capstone_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(80) NOT NULL,
  description VARCHAR(200) NOT NULL,
  CONSTRAINT uq_capstone_permissions_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS capstone_user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_capstone_user_roles_user
    FOREIGN KEY (user_id) REFERENCES capstone_users (id) ON DELETE CASCADE,
  CONSTRAINT fk_capstone_user_roles_role
    FOREIGN KEY (role_id) REFERENCES capstone_roles (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_capstone_user_roles_role_user
  ON capstone_user_roles (role_id, user_id);

CREATE TABLE IF NOT EXISTS capstone_role_permissions (
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_capstone_role_permissions_role
    FOREIGN KEY (role_id) REFERENCES capstone_roles (id) ON DELETE CASCADE,
  CONSTRAINT fk_capstone_role_permissions_permission
    FOREIGN KEY (permission_id) REFERENCES capstone_permissions (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_capstone_role_permissions_permission_role
  ON capstone_role_permissions (permission_id, role_id);

-- 幂等基础种子。
INSERT INTO capstone_roles (code, name)
VALUES ('admin', '管理员'), ('member', '普通成员')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO capstone_permissions (code, description)
VALUES
  ('user:read', '读取用户'),
  ('user:write', '创建或修改用户')
ON CONFLICT (code) DO UPDATE SET description = EXCLUDED.description;

INSERT INTO capstone_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM capstone_roles AS r
JOIN capstone_permissions AS p
  ON (r.code = 'admin' AND p.code IN ('user:read', 'user:write'))
  OR (r.code = 'member' AND p.code = 'user:read')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- 事务示例：创建用户并分配 member 角色。
-- ROLLBACK 确保演示用户不会保留。
BEGIN;

INSERT INTO capstone_users (email, display_name, status)
VALUES ('transaction-demo@example.test', '事务演示用户', 'active');

INSERT INTO capstone_user_roles (user_id, role_id)
SELECT u.id, r.id
FROM capstone_users AS u
CROSS JOIN capstone_roles AS r
WHERE u.email = 'transaction-demo@example.test'
  AND r.code = 'member';

SELECT u.id, u.email, r.code AS role_code
FROM capstone_users AS u
JOIN capstone_user_roles AS ur ON ur.user_id = u.id
JOIN capstone_roles AS r ON r.id = ur.role_id
WHERE u.email = 'transaction-demo@example.test';

ROLLBACK;

-- 稳定分页的用户列表。真实接口把常量改成驱动参数，并限制 pageSize。
SELECT u.id, u.email, u.display_name, u.status, u.created_at
FROM capstone_users AS u
WHERE u.status = 'active'
  AND EXISTS (
    SELECT 1
    FROM capstone_user_roles AS ur
    JOIN capstone_roles AS r ON r.id = ur.role_id
    WHERE ur.user_id = u.id
      AND r.code = 'member'
  )
ORDER BY u.created_at DESC, u.id DESC
LIMIT 20;

-- 用户的有效权限；DISTINCT 消除多个角色带来的重复权限。
SELECT DISTINCT p.code
FROM capstone_user_roles AS ur
JOIN capstone_role_permissions AS rp ON rp.role_id = ur.role_id
JOIN capstone_permissions AS p ON p.id = rp.permission_id
WHERE ur.user_id = 1
ORDER BY p.code;

EXPLAIN
SELECT u.id, u.email, u.display_name, u.status, u.created_at
FROM capstone_users AS u
WHERE u.status = 'active'
ORDER BY u.created_at DESC, u.id DESC
LIMIT 20;

